title: Yalin's Research Blog
email: ylliu@hkmu.edu.hk
description: A blog and portfolio by Yalin Liu
theme: minima
baseurl: "" # Set to "/repo" if hosted at username.github.io/repo
url: "https://yalin-liu.github.io" # Replace with your GitHub Pages URL
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
category_dir: categories
tag_dir: tags
collections:
  pages:
    output: true
    permalink: /:name
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-paginate
#   - jekyll-multiple-languages-plugin
# plugins:
#   - jekyll-polyglot
# languages: ["en", "zh-CN", "zh-TW"]
# default_lang: "en"
# exclude_from_localization: ["css", "assets", "images", "js"]
# parallel_localization: true
# lang_from_path: true
# permalink: pretty
social_links:
  hkmu_scholar: "https://scholars.hkmu.edu.hk/en/persons/yalin-liu/publications/"
  google_scholar: "https://scholar.google.com/citations?user=boJGB9cAAAAJ&hl=zh-CN"
  research_gate: "https://www.researchgate.net/profile/Yalin-Liu/research?ev=prf_act"
  linkedin: "https://www.linkedin.com/in/alin-yalin-liu"
  orcid: "https://orcid.org/0000-0003-2870-4598"
  github: https://github.com/yalin-liu